/** Generated by YAKINDU Statechart Tools code generator. */
package mythermostat.thermostat;

import mythermostat.IStatemachine;
import mythermostat.ITimerCallback;

public interface IThermostatStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseMode();
		
		public void raiseSet();
		
		public void raiseOpenWindow();
		
		public void raiseCloseWindow();
		
		public long getTime();
		
		public void setTime(long value);
		
		public long getHour();
		
		public void setHour(long value);
		
		public long getDay();
		
		public void setDay(long value);
		
		public long getNight();
		
		public void setNight(long value);
		
		public long getMinT();
		
		public void setMinT(long value);
		
		public long getMaxT();
		
		public void setMaxT(long value);
		
		public long getDayT();
		
		public void setDayT(long value);
		
		public long getNightT();
		
		public void setNightT(long value);
		
		public long getInT();
		
		public void setInT(long value);
		
		public boolean getIsOpen();
		
		public void setIsOpen(boolean value);
		
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceOperationCallback {
	
		public long outTemp();
		
	}
	
	public SCInterface getSCInterface();
	
}
